### ISSUE TITLE
B tv (SKbroadband's iptv)를 추가하고 싶습니다.

### ISSUE THREAD

**Issue by dicapriokim** [PRProd/HA-Firemote#455] opened 2024-06-28 02:47 UTC
### Language Code

ko

### Apple TV source_list

```text
friendly_name: Apple_tv_4K
supported_features: 450487
source_list: App Store, Arcade, B tv, Disney+, FaceTime, Infuse, Netflix, Speedtest, TV, YouTube, zFuse TV Pro, Search, Settings, Picture, Music, Computer, Podcast
app_id: com.skbroadband.BtvOnA
app_name: B tv
media_position_updated_at: 2024-06-28T02:16:15.583713+00:00
```

### Translation Chart

```text
01. App Launch Button => 
02. App Launcher Relative Scale =>
03. Apple Computers => 
04. Apple Music => 
05. Apple Photos => 
06. Associated => 
07. bottom => 
08. Compatibility Mode => 
09. Computers => 
10. Custom Remote Skin =>
11. Default for => 
12. Device Family => 
13. Device Model => 
14. Device Name Text Color => 
15. DPad Style =>
16. Entity => 
17. Function: Captions => 
18. Function: Channel + => 
19. Function: Channel - => 
20. Function: Control Center => 
21. Function: Find My Remote => 
22. Function: Mute => 
23. Function: Next => 
24. Function: Pairing => 
25. Function: Previous => 
26. Function: Reboot => 
27. Function: Search => 
28. Function: Settings => 
29. Function: Skip Backward => 
30. Function: Skip Forward => 
31. Function: Switch Apps => 
32. Function: System Update => 
33. Function: Volume + => 
34. Function: Volume - => 
35. hidden => 
36. Hide frames around button groups =>
37. Music => 
38. Name Position => 
39. optional => 
40. Photos => 
41. Remote Style => 
42. Scale => 
43. Settings => 
44. Search => 
45. top => 
46. Visible Device Name =>
```

### Additional Comments (optional)

![스크린샷 2024-06-28 113655](https://github.com/PRProd/HA-Firemote/assets/140711196/ccb36613-6ad9-45f4-ae2f-fb61fe129ce4)

**Comment by PRProd** [comment] 2024-06-28 14:49
Closing as invalid - mis-categorized duplicate of #448

**Closed by PRProd** 2024-06-28 14:49 UTC
Labels: enhancement, Region Issue
