### ISSUE TITLE
[New App Shortcut]: MyCanal

### ISSUE THREAD

**Issue by bozzoyann** [PRProd/HA-Firemote#33] opened 2023-02-06 19:33 UTC
### App Name

MyCanal

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

Hello,

Thanks a lot for this card. Very nice and good job

The app "MyCanal" is quite popular in France.
Here is the app_id : 

`com.canal.android.canal`

And this is the official website of the webapp version
https://www.canalplus.com/

Thanks again

**Comment by PRProd** [comment] 2023-02-07 22:43
@bozzoyann - Thanks for your request!

I found the Canal+ app in the official fire tv store for download, but it is not available in my region, so I am unable to test the shortcut for myself.  Please download the latest Firemote pre-release [v1.10.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v1.10.4.2) and verify if the app shortcut button is working as expected.

Thanks!

**Comment by PRProd** [comment] 2023-02-08 22:02
Version [1.11.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.1) has been released and it contains your requested app shortcut addition.  Because this app is not available in my region, I've been unable to test the shortcut to make sure it works as intended.  That being said, I added this untested app shortcut to this official release because there were several other issues waiting for resolution in the next official release, so I wanted to get it out there as soon as I could.  For now, I'm going to close this issue, but please let me know if you try it out later and find that the app shortcut does not function as intended, and I will work with you to get it working properly. 

Thanks for your contribution!

**Closed by PRProd** 2023-02-08 22:02 UTC
Labels: enhancement, New App Shortcut

**Comment by bozzoyann** [comment] 2023-02-09 16:43
Hello, 

The app shortcut is working very fine. At it detects perfectly when the app is running.

Just a remark, can the "running" app color can be : #232227   ?
it is the offcial dark grey of CANAL

Thank you

**Comment by PRProd** [comment] 2023-02-09 16:54
@bozzoyann  - Absolutely!   I found that other hideous color on their website, so I chose that initially.

I will make that change on the main branch now, and it will for sure be included in the next official release.

**Comment by PRProd** [comment] 2023-02-10 20:56
@bozzoyann - Official release [v1.11.2](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.2) is available now with your change request included.

**Comment by bozzoyann** [comment] 2023-02-26 15:57
@PRProd - Thanks, everything works well for 1 month.
Thanks a lot
