### ISSUE TITLE
[Feature Request]: Add support for Samsung Smart TV

### ISSUE THREAD

**Issue by 414ND1N** [PRProd/HA-Firemote#582] opened 2024-12-12 02:22 UTC
### Feature Request

Would it be possible to add support for Samsung Smart TV integration and his remote integration ? I would appreciate it. 

### Additional Comments (optional)

With the current options it is difficult to make the app launcher buttons work.

**Comment by PRProd** [comment] 2024-12-16 16:38
Greetings @414ND1N (and @Aenos85)!

Thank you for your request!  As Firemote's popularity has been growing, I've received many requests similar to yours to add new device families.  Because of the overwhelming number of requests, I've been hosting a [poll](https://github.com/PRProd/HA-Firemote/discussions/41) where Firemote users can vote to guide the direction of the Firemote project.

Please visit [Poll: Vote for what gets added next! #41](https://github.com/PRProd/HA-Firemote/discussions/41) and cast your vote there.  Good luck!

-Doug
****
 - duplicate of https://github.com/PRProd/HA-Firemote/discussions/561

**Closed by PRProd** 2024-12-16 16:38 UTC
Labels: enhancement
