### ISSUE TITLE
Apple TV Home button not working

### ISSUE THREAD

**Issue by shooln** [PRProd/HA-Firemote#521] opened 2024-10-08 19:54 UTC
### Describe the bug

Failed to perform the action remote/send_command. top_menu is not supported

### To Reproduce

Setup apple tv remote for apple TV HD onwards

### Expected Behavior

Home button pressed and no error message

### Which Type of Device Do You Own?

Apple Tv 4K 2023

**Comment by PRProd** [comment] 2024-10-08 20:47
Greetings @shooln!

I'm not entirely sure why this is happening to you.  I am not able to reproduce the issue on my end, and [the integration documentation](https://www.home-assistant.io/integrations/apple_tv#remote) still shows that ``top_menu`` is a valid remote command to send.

I have two and a half theories:

1. Your AppleTV integration needs to be reloaded.  (This happens sometimes, not sure why)  Take a look at what I wrote [in discussion #380](https://github.com/PRProd/HA-Firemote/discussions/380#discussioncomment-9240129) to see how to reload the integration.
2. Something is misconfigured in your Firemote config.  If the above step doesn't work, can you reply here with the YAML from your Firemote config?
3. Other - Have you tried restarting your Home Assistant and your Apple TV?

Please let me know what happens!  I really want to get this fixed for you!

-Doug

**Comment by PRProd** [comment] 2024-10-18 04:24
@shooln ~

Have you had a chance to look at this yet?  I'm wondering if you still need any help.  Please let me know.

-Doug

**Comment by shooln** [comment] 2024-10-19 08:37
Hi @PRProd 

apologies for the delayed reply. I tried all the steps mentioned above and still get the same error. yaml is as follows

`type: panel\npath: apple-tv-remote\ntitle: Apple TV Remote\ncards:\n  - type: custom:firemote-card\n    entity: media_player.living_room\n    device_family: apple-tv\n    device_type: appletv-4k-gen3\n    compatibility_mode: default\n    apple_tv_remote_entity: remote.living_room\n    scale: \"120\"\n    defaultRemoteStyle_override: \"\"\n    app_launch_1: plex\n    app_launch_2: crave-tv\n    app_launch_4: infuse\n    app_launch_3: disney-plus\n    visible_name_text: \"\"\n    name_position: hidden\n    app_launch_5: \"\"\nicon: mdi:apple`

please note I am running tvOS 18.1 22j5567a

Thanks for investigating and looking into this issue!

**Comment by thecreaser** [comment] 2024-10-26 10:36
1st Gen 4k Apple TV
I've just installed firemote and was having perhaps similar problems.  The app launch buttons worked but nothing else.
I had the apple remote with me at my PC desk a distance 10m away from the apple TV box with a wall between the two.  The physical remote did not work 100% with line-of-sight at that distance.
When I placed the physical remote close the the Apple TV box then _everything_ started working correctly.
It seems that the physical remote and ATV need to be close enough to communicate.
It implies that Firemote doesn't fully work if a user has no physical remote.
My suggestion would be to add this info to the documentation.  I was totally stumped before I chanced on the solution.  
HTH

**Comment by thecreaser** [comment] 2024-10-26 20:37
> 1st Gen 4k Apple TV I've just installed firemote and was having perhaps similar problems. The app launch buttons worked but nothing else. I had the apple remote with me at my PC desk a distance 10m away from the apple TV box with a wall between the two. The physical remote did not work 100% with line-of-sight at that distance. When I placed the physical remote close the the Apple TV box then _everything_ started working correctly. It seems that the physical remote and ATV need to be close enough to communicate. It implies that Firemote doesn't fully work if a user has no physical remote. My suggestion would be to add this info to the documentation. I was totally stumped before I chanced on the solution. HTH

This behaviour has since stopped.  Only the app launch buttons work.
Error message: _failed to perform the action remote/send_command. unknown error_

**Comment by thecreaser** [comment] 2024-10-26 20:53
Core log after pressing a button below.  Could it be related to [issue #126754](https://github.com/home-assistant/core/issues/126754) for the websocket api?

> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/websocket_api/commands.py:245
> integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 21:45:33 (1 occurrences)
> Last logged: 21:45:33
> [547778073008] Unexpected exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
>     await semaphore.acquire()
>   File "/usr/local/lib/python3.12/asyncio/locks.py", line 386, in acquire
>     await fut
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
>     response = await hass.services.async_call(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/apple_tv/remote.py", line 94, in async_send_command
>     await attr_value()
>   File "/usr/local/lib/python3.12/site-packages/pyatv/core/facade.py", line 107, in menu
>     return await self.relay("menu")(action=action)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/mrp/__init__.py", line 404, in menu
>     await _send_hid_key(self.protocol, "menu", action)
>   File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/mrp/__init__.py", line 310, in _send_hid_key
>     await _do_press(keycode, False)
>   File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/mrp/__init__.py", line 303, in _do_press
>     await protocol.send_and_receive(messages.create(protobuf.GENERIC_MESSAGE))
>   File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
>     return await self._receive(identifier, timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
>     async with async_timeout.timeout(timeout):
>   File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
>     self._do_exit(exc_type)
>   File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
>     raise asyncio.TimeoutError
> TimeoutError
>

**Comment by PRProd** [comment] 2024-10-27 18:49
@shooln & @thecreaser ~

Although Firemote is capable of doing things that cards typically do not do, Firemote it not an integration, it is just a card.  [Because this is how Firemote works](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices), any issues that are present in Home Assistant, or within the integrations that Firemote card depends on ([Apple TV](https://www.home-assistant.io/integrations/apple_tv), [Android TV/Android Debug Bridge](https://www.home-assistant.io/integrations/androidtv), [Android TV Remote](https://www.home-assistant.io/integrations/androidtv_remote/), [roku](https://www.home-assistant.io/integrations/roku/), etc)

The issues that each of you have described are not reproducible in my lab.  I don't doubt at all that they ARE happening in your environments, but I do not think that they are present in every situation.

I recommend (as @thecreaser has already done) looking through Github issues that have already been opened against these kinds of behaviors to see what kind of progress is being made there.  If you cannot find any open issues, it's possible that you are the first to find them, and that YOU should open new issues with the integration maintainers.  I've personally done this a few times when I've found things in the Roku integration that weren't quite working as I expected.

I'll leave this issue open for a while longer for anyone else who might want to comment, and/or share with us what kind of additional research has been found.

I apologize that I cannot fix these issues, but their underlying causes are not due to the Firemote code, nor can they be fixed by any adjustments in the Firemote code.

-Doug

**Closed** 2024-11-06 16:20 UTC
Labels: Upstream Dependency Issue
