### ISSUE TITLE
[New App Shortcut]: 

### ISSUE THREAD

**Issue by DewiSoft** [PRProd/HA-Firemote#592] opened 2024-12-24 17:06 UTC
### App Name

MagisTV

### Device Platform

onn.

### App Store Link and/or URL to .apk file if sideloaded

https://themagistv.com/WNOTi6IlZA9oyic/file

### Required Information

https://themagistv.com/

**Comment by PRProd** [comment] 2024-12-30 23:27
Closing - Duplicate of #593

**Closed by PRProd** 2024-12-30 23:27 UTC
Labels: duplicate
