### ISSUE TITLE
Remote „picture“ looks distorted after installing HA core 2024.8

### ISSUE THREAD

**Issue by amstermk** [PRProd/HA-Firemote#478] opened 2024-08-09 16:34 UTC
### Describe the bug

On iPads the picture of the apple-remote looks distorted after installing HA core 2024.8. See enclosed jpg.

![IMG_1033](https://github.com/user-attachments/assets/0df306db-4339-4d09-9d89-e25c19022afb)

On iPhone or Firetablet HD10 it looks fine/as it should

### To Reproduce

Just add the fireremote card to dashboard on an iPad

### Expected Behavior

I expect the remote to look like it should on iPad

### Which Type of Device Do You Own?

AppleTV 4k gen 2 2021
IPad Pro 11inch 2nd generation

**Comment by PRProd** [comment] 2024-08-09 16:38
Greetings @amstermk!

Thank you for your report.  I have also noticed this issue, and already opened a bug report at https://github.com/home-assistant/iOS/issues/2908 - I will reference this report over there too.

-Doug

**Comment by bpectel** [comment] 2024-08-10 20:10
I’m having the same problem

**Comment by tanderson1973** [comment] 2024-08-10 23:43
Having similar issues using Firemote with dashboa
![Uploading HA application MacOS - Amazon Fire - JVC.png…]()
rds/cads for JVC and Apple remotes, only in HA desktop application (MacOS), when using via chrome browser appears as should.

**Comment by vasqued2** [comment] 2024-08-11 11:47
Here is a workaround that works for me and I am curious if it works for others.  If it consistently works, I expect it will help find the root cause.

1. Create a new Firemote card on the same dashboard tab that your other card/cards are on.  It can be any type of remote.
2. Go into Show Code Editor mode and change the entity to any **_invalid_** entity name and save the new card.  This should create a text visual for the card that simply says "Unknown entity: Invalid Entity Name from the YAML."  I used the same English name I use for my remote.
3. Move this new card so it is the first one in the dashboard.
4. Refresh the dashboard on the device having problems to the Unknown entity card displays.
5. All the other cards should magically render correctly once refreshed.

The downside is you have the Unknown Entity text as the first item on your dashboard tab.  I am curious if it works for everyone.

Example after adding a new card for with an invalid entity name and putting it first.

![image](https://github.com/user-attachments/assets/c21bf4e2-a8be-441e-844d-3793785c83e0)

**Comment by amstermk** [comment] 2024-08-11 12:29
Tried your workaround… and yes that works for me. So one positve feedback!

**Comment by nsleigh** [comment] 2024-08-11 14:49
Works for me too. I was able to delete the temp card and it was still ok.

**Comment by PRProd** [comment] 2024-08-11 18:00
@vasqued2 ~ Works on my iPad too!  You're a hero!

**Comment by vasqued2** [comment] 2024-08-11 19:08
@PRProd I was chasing ghosts until you pointed out the iPad/HA 2024.8.0 connection.

Once I confirmed the workaround for my card, I wanted to try it with others to see how consistent it was.  Plus I was able to replace my old hacked-together Roku remote control tab with the much simpler and prettier Firemote in the process.

Thanks for your help and the card.

**Comment by PRProd** [comment] 2024-08-11 19:11
Thanks for your kind words @vasqued2!  It's so awesome to be a part of a group of people who volunteer and help each other out!

**Comment by nsleigh** [comment] 2024-08-12 14:29
> This card MUST be first for the temp hack to work
YYMV but I found it just had to be before the working remote.

**Comment by PRProd** [comment] 2024-08-16 15:06
### Update
https://github.com/home-assistant/iOS/issues/2908 has been closed after a lot of very fruitful conversation by a lot of very smart people.

PR https://github.com/home-assistant/iOS/pull/2918 has been merged.  Another PR https://github.com/home-assistant/frontend/pull/21695 has been made with the frontend team that should complete the fix for iPad rendering.

After these fixes are officially deployed for iPad OS, this issue still might persist with some older/legacy tablet devices.  I'm unsure about the impact to current Firemote users at this time.  Details here: https://github.com/home-assistant/iOS/issues/2908#issuecomment-2293615805

**Comment by piitaya** [comment] 2024-08-16 15:17
I open a PR to fix in the [weather chart card repository](https://github.com/mlamberts78/weather-chart-card/pull/223). Similar fix can be added to this repository to supports legacy browsers.

**Comment by PRProd** [comment] 2024-08-26 15:45
The rendering issue within iPadOS has been fixed in the latest companion app update, [2024.8](https://github.com/home-assistant/iOS/releases/tag/release%2F2024.8%2F2024.783) released Aug 22, 2024.

Please download the [latest version from the app store](https://apps.apple.com/us/app/home-assistant/id1099568401).

Closing issue.

**Closed by PRProd** 2024-08-26 15:45 UTC
Labels: Upstream Dependency Issue, Workaround Available
