### ISSUE TITLE
Apple TV Remotes do not display correctly in HASS Mac App

### ISSUE THREAD

**Issue by parchmaf** [PRProd/HA-Firemote#500] opened 2024-09-04 17:02 UTC
### Describe the bug

I'm not sure if this is a bug or not, but I use several Apple TV remotes and they no longer work correctly within the Home Assistant app on Mac.  They do work fine with the HASS app on my iphone / ipad or Chrome on my Mac.  I tried clearing the frontend cache and that did nothing.  Is there anything I can do to fix this for the HASS Mac app?  I attached a photo of what the remote looks like.

<img width="175" alt="Screenshot 2024-09-04 at 11 55 33 AM" src="https://github.com/user-attachments/assets/2594a3c3-d673-4d9b-954c-2115cf9c6ba5">

### To Reproduce

Use a configured Firemote with the HASS Mac app

### Expected Behavior

The remote should looks normal, not squashed and un-usable

### Which Type of Device Do You Own?

Apple TV 3rd and 4th gen

### Troubleshooting Steps Completed

Clearing the frontend cache and that did nothing.  I also deleted and re-installed Firemote.  I just upgraded to the latest version today.

**Comment by PRProd** [comment] 2024-09-04 17:17
Hello there @parchmaf!

This is 100% related to issue #478 which was only appearing on iPads and some older tablets/browsers after updating to HA 2024.8 or newer.  That issue [was fixed](https://github.com/PRProd/HA-Firemote/issues/478#issuecomment-2310520411) after a new version of the iPadOS was released.

I wasn't aware that there was a "Home Assistant App on Mac" - is that different from the iPadOS companion app?

Do you see this same behavior when viewing Home Assistant through a browser on your mac?

**Comment by parchmaf** [comment] 2024-09-04 18:26
Thanks for the quick response.  The app is a Mac app and not an iPad app running on Mac.  It is also the latest version in the app store.  Firemote does work correctly with Chrome and Safari.

**Comment by PRProd** [comment] 2024-09-04 21:00
@parchmaf ~

Looking into this some more for the macOS companion app, I'm seeing a [pull request](https://github.com/home-assistant/frontend/pull/21724) that was merged **Aug 21, 2024** which looks like it should have fixed this issue.

Here's my dilemma ~ I do not have a mac on hand to do any testing, nor do I fully understand how the issue was solved for the iPadOS and the macOS companion apps.  I do know that the iPad app was updated and pushed to the store, and I can confirm that fixed the issue.  I do not know the situation surrounding the macOS companion app.

Sorry to bug you @steverep ~ can you educate me a little here?

-Doug

**Comment by steverep** [comment] 2024-09-05 00:55
The frontend PR you referenced will fix it for macOS 12+ but you need to update HA to 2024.9 first.

**Comment by parchmaf** [comment] 2024-09-05 15:20
Thanks!  That fixed the issue.  I appreciate it!

**Comment by PRProd** [comment] 2024-09-05 15:34
That's great news @parchmaf!  THANK YOU SO MUCH for responding, @steverep!

**Closed by PRProd** 2024-09-05 15:34 UTC
